---
title: "mrmac"
author: "jquery404"
date: "6/26/2023"
output: html_document
---

```{r}
library(ggplot2)
library(ggpubr)
library(dplyr)
library(likert) 

coloring = c("#E76469", "#F8D85E","#EDA645","#D1B0B3","#8C99A6","#ADD299","#4FA490","#3B7F9F")
fontsize = 14
dodge = .75
```


##############################
###### Social Presence #######
##############################

```{r}
social_data =read.csv('csv/social_presence.csv', sep=",")
attach(social_data)

# analysis of variance
anova = aov(score ~params, data=social_data)
summary(anova)

# pairwise comp
tukey = TukeyHSD(anova)
print(tukey)

# grouped box plot
social_plt <- ggplot(data = social_data, mapping = aes(x = params, y = score, fill = role)) +
  stat_boxplot(aes(fill = role), geom = "errorbar", width = 0.2, position = position_dodge(dodge)) +
  geom_boxplot(aes(fill = role), width = dodge, coef = 0, outlier.alpha = 0, show.legend = F) +
  # geom_point(position=position_jitterdodge(dodge.width=0.9)) +
  stat_compare_means(aes(label = paste0("p = ", after_stat(p.format))), method="wilcox.test") + 
  stat_summary(aes(fill = role), fun = mean, 
               geom= "point", shape = 4, size = 5, colour= "black", 
               position = position_dodge(width = dodge)) +
  stat_summary(aes(fill = role), fun = median,
               geom = "crossbar", fatten = .1, width = .4*dodge, color = "black",
               position = position_dodge(width = dodge)) +
  scale_fill_manual(name= "role", values = c("#E76469", "#F8D85E")) +
  scale_color_manual(name = "role", values = c("#E76469", "#F8D85E")) + 
  scale_y_continuous(minor_breaks = seq(0, 7, 1), breaks = seq(1, 7.1, by=1), limits=c(1,7.1)) + 
  theme_bw() + 
  theme(axis.line = element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.x = element_text(color="black", size=fontsize),
        axis.text.y = element_text(color="black", size=fontsize),
        text = element_text(size=fontsize),
        strip.background = element_blank(),
        plot.background = element_blank(),
        plot.margin = unit(c(0.005, .025, 0, 0), "null"),
        panel.border = element_blank(),
        panel.spacing = unit(c(0, 0, 0, 0), "null"),
        #panel.grid.major = element_blank(),
        legend.position = c(.95, 0.2),
        legend.justification = c("right", "top"),
        legend.title=element_blank(),
        legend.text=element_text(size=fontsize),
        legend.box.just = "right",
        legend.box.background = element_rect(fill = "white", color = "black", size = 1))

social_plt
# saving the final figure
ggsave("out/_social_presence.pdf", width = 8, height = 4, dpi = 1000)
```

##############################
###### Spatial Presence ######
##############################

```{r}
spatial_data=read.csv('csv/spatial_presence.csv', sep=",")

sp=read.csv('csv/sp.csv', sep=",")
iv=read.csv('csv/involvement.csv', sep=",")
gp=read.csv('csv/gp.csv', sep=",")
rl=read.csv('csv/real.csv', sep=",")
names(sp)
names(spatial_data)

# analysis of variance
anova = aov(score ~params, data=spatial_data)
summary(anova)
shapiro.test(spatial_data$score)


# pairwise comp
tukey = TukeyHSD(anova)
print(tukey)

# wilcox
boxplot(sp$VR, sp$AR, horizontal = T)
text(x=fivenum(sp$VR),labels=fivenum(sp$VR), y = 1.50)
wsr_sp <- wilcox.test(sp$VR, sp$AR, mu=0, alt="two.sided", paired=T, conf.int=T, conf.level = 0.99, exact=F)
print(wsr_sp)





# grouped box plot
spatial_plt <- ggplot(data = spatial_data, mapping = aes(x = params, y = score, fill = role)) +
  stat_boxplot(aes(fill = role), geom = "errorbar", width = 0.2, position = position_dodge(dodge)) +
  geom_boxplot(aes(fill = role), width = dodge, coef = 0, outlier.alpha = 0, show.legend = F) +
  # geom_point(position=position_jitterdodge(dodge.width=0.9)) +
  stat_compare_means(aes(label = paste0("p = ", after_stat(p.format))), method="wilcox.test") + 
  stat_summary(aes(fill = role), fun = mean, 
               geom= "point", shape = 4, size = 5, colour= "black", 
               position = position_dodge(width = dodge)) +
  stat_summary(aes(fill = role), fun = median,
               geom = "crossbar", fatten = .1, width = .4*dodge, color = "black",
               position = position_dodge(width = dodge)) +
  scale_fill_manual(name= "role", values = c("#E76469", "#F8D85E"))+
  scale_color_manual(name = "role", values = c("#E76469", "#F8D85E")) + 
  scale_y_continuous(minor_breaks = seq(0, 7, 1), breaks = seq(1, 7.1, by=1), limits=c(1,7.1)) +
  theme_bw() +
  theme(axis.line = element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.x = element_text(color="black", size=fontsize),
        axis.text.y = element_text(color="black", size=fontsize),
        text = element_text(size=fontsize),
        strip.background = element_blank(),
        plot.background = element_blank(),
        plot.margin = unit(c(0.005, .025, 0, 0), "null"),
        panel.border = element_blank(),
        panel.spacing = unit(c(0, 0, 0, 0), "null"),
        #panel.grid.major = element_blank(),
        legend.position = c(.95, 0.2),
        legend.justification = c("right", "top"),
        legend.title=element_blank(),
        legend.text=element_text(size=fontsize),
        legend.box.just = "right",
        legend.box.background = element_rect(fill = "white", color = "black", size = 1))
spatial_plt

ggsave("out/_spatial_presence.pdf", width = 7, height = 4, dpi = 1000)
```


##############################
###### RTLX ######
##############################

```{r}
gfg=read.csv('csv/nasa_tlx.csv', sep=",")
param_order <- c("Mental", "Physical", "Temporal", "Performance", "Effort", "Frustration", "Overall")
gfg$params <- factor(gfg$params, levels = param_order)


# grouped box plot
ggplot(data = gfg, mapping = aes(x = params, y = score, fill= role)) +
  stat_boxplot(aes(fill = role), geom = "errorbar", width = 0.2, position = position_dodge(dodge)) +
  geom_boxplot(aes(fill = role), width = dodge, coef = 0, outlier.alpha = 0, show.legend = F) +
  stat_compare_means(aes(label = paste0("p = ", after_stat(p.format))), method="wilcox.test") + 
  stat_summary(aes(fill = role), fun = mean, 
               geom= "point", shape = 4, size = 5, colour= "black", 
               position = position_dodge(width = dodge)) +
  stat_summary(aes(fill = role), fun = median,
               geom = "crossbar", fatten = .1, width = .4*dodge, color = "black",
               position = position_dodge(width = dodge)) +
  labs(x = NULL, y = NULL) + 
  scale_fill_manual(name= "role", values = c("#E76469", "#F8D85E")) +
  scale_color_manual(name = "role", values = c("#E76469", "#F8D85E")) + 
  theme_bw() +
  theme(axis.line = element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.x = element_text(color="black", size=fontsize),
        axis.text.y = element_text(color="black", size=fontsize),
        text = element_text(size=fontsize),
        strip.background = element_blank(),
        plot.background = element_blank(),
        plot.margin = unit(c(0.005, .025, 0, 0), "null"),
        panel.border = element_blank(),
        panel.spacing = unit(c(0, 0, 0, 0), "null"),
        #panel.grid.major = element_blank(),
        legend.position = c(.95, 0.2),
        legend.justification = c("right", "top"),
        legend.title=element_blank(),
        legend.text=element_text(size=fontsize),
        legend.box.just = "right",
        legend.box.background = element_rect(fill = "white", color = "black", size = 1))

# saving the final figure
ggsave("out/_rtlx.pdf", width = 10, height = 4, dpi = 1000)
```




#######################################
# preference horizontal box plot #
#######################################


```{r}
gfg=read.csv('csv/preference.csv', sep=",")


# grouped box plot
level_order <- c(
  "Q10 ...overall experience comfortable for you?",
  "Q9 ...feel the presence of the remote users?",
  "Q8 ...feel you were there in the remote space?",
  "Q7 ...tools were sufficient to perform your tasks?",
  "Q6 ...got necessary feedback from others?",
  "Q5 ...comfortable communicating with remote user avatar?",
  "Q4 ...able to effectively communicate with others?",
  "Q3 ...rate the overall audio quality?",
  "Q2 ...rate the overall video quality?",
  "Q1 ...able to clearly hear and see in the remote space?")

ggplot(data=gfg, mapping= aes(x=factor(qus, level = level_order), y=ans, fill=role)) +
  stat_boxplot(aes(fill = role), geom = "errorbar", width = 0.2, position = position_dodge(dodge)) +
  geom_boxplot(aes(fill = role), width = .75*dodge, position = position_dodge(dodge), coef = 0, outlier.alpha = 0, show.legend = F) +
  stat_summary(aes(fill = role), fun = mean, 
               geom= "point", shape = 4, size = 2*dodge, colour= "black", 
               position = position_dodge(width = dodge)) +
  labs(x = NULL, y = NULL) + 
  scale_fill_manual(name= "role", values = c("#E76469", "#F8D85E")) +
  scale_color_manual(name = "role", values = c("#E76469", "#F8D85E")) + 
  guides(fill=guide_legend(title="")) +
  scale_y_continuous(minor_breaks = seq(0, 7, 1), breaks = seq(1, 7.1, by=1), limits=c(1,7.1)) + 
  coord_flip(ylim = c(0, 7)) +
  theme_bw() +
  theme(axis.line = element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.x = element_text(color="black", size=fontsize),
        axis.text.y = element_text(color="black", size=fontsize),
        text = element_text(size=fontsize),
        strip.background = element_blank(),
        plot.background = element_blank(),
        plot.margin = unit(c(0.005, .025, 0, 0), "null"),
        panel.border = element_blank(),
        panel.spacing = unit(c(0, 0, 0, 0), "null"),
        legend.position = "none")

ggsave("out/_preference.pdf", width = 10, height = 6, dpi = 1000)
```